-- =====================================================================
-- L1 (silver) — SAP_BDC_L1 curated tables
-- The SAP BDC Sales/CRM/Product standard data products landed and curated
-- into a governed L1 layer (sales orders, opportunities, customers, product
-- master + full product plant/valuation extensions).
-- =====================================================================

create or replace schema SAP_SALES_360.SAP_BDC_L1 COMMENT='SAP BDC Layer 1 - Raw/Source Data';

create or replace TABLE SAP_SALES_360.SAP_BDC_L1.CRM_OPPORTUNITY_ACTIVITY (
	ACTIVITY_ID VARCHAR(16777216) NOT NULL COMMENT 'The ID of the activity.',
	OPPORTUNITY_ID VARCHAR(16777216) COMMENT 'The ID of the opportunity.',
	SAP_CUSTOMER_KEY VARCHAR(16777216) COMMENT 'The SAP customer key.',
	ACTIVITY_TYPE VARCHAR(16777216) COMMENT 'The type of the activity.',
	SUBJECT VARCHAR(16777216) COMMENT 'The subject of the email or meeting.',
	DESCRIPTION VARCHAR(16777216) COMMENT 'A description of the activity.',
	STATUS VARCHAR(16777216) COMMENT 'The current status of the activity.',
	PRIORITY VARCHAR(16777216) COMMENT 'The priority level of the activity.',
	ACTIVITY_DATE DATE COMMENT 'The date of the activity.',
	START_TIME TIMESTAMP_LTZ(9) COMMENT 'The start time of the activity.',
	END_TIME TIMESTAMP_LTZ(9) COMMENT 'The end time of the activity.',
	DURATION_MINUTES NUMBER(10,0) COMMENT 'The duration of the activity in minutes.',
	OWNER_ID VARCHAR(16777216) COMMENT 'The ID of the owner of the activity.',
	OWNER_NAME VARCHAR(16777216) COMMENT 'The name of the owner of the activity.',
	ASSIGNED_TO_ID VARCHAR(16777216) COMMENT 'The ID of the person assigned to the activity.',
	ASSIGNED_TO_NAME VARCHAR(16777216) COMMENT 'The name of the person assigned to the activity.',
	CONTACT_ID VARCHAR(16777216) COMMENT 'The ID of the contact person.',
	CONTACT_NAME VARCHAR(16777216) COMMENT 'The name of the contact person.',
	CONTACT_TITLE VARCHAR(16777216) COMMENT 'The title of the contact person.',
	OUTCOME VARCHAR(16777216) COMMENT 'The outcome of the activity.',
	NEXT_STEPS VARCHAR(16777216) COMMENT 'The next steps for the activity.',
	CREATED_DATE TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'The date the activity was created.',
	LAST_MODIFIED_DATE TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'The date the activity was last modified.',
	IS_DELETED BOOLEAN DEFAULT FALSE COMMENT 'Whether the activity is deleted.',
	CALL_DIRECTION VARCHAR(16777216) COMMENT 'The direction of the call.',
	CALL_DISPOSITION VARCHAR(16777216) COMMENT 'The outcome of the call.',
	MEETING_TYPE VARCHAR(16777216) COMMENT 'The type of the meeting.',
	MEETING_LOCATION VARCHAR(16777216) COMMENT 'The location of the meeting.',
	EMAIL_TEMPLATE VARCHAR(16777216) COMMENT 'The template used for the email.',
	EMAIL_OPENED BOOLEAN COMMENT 'Whether the email was opened.',
	EMAIL_CLICKED BOOLEAN COMMENT 'Whether the email was clicked.',
	primary key (ACTIVITY_ID)
);
create or replace TABLE SAP_SALES_360.SAP_BDC_L1.CRM_OPPORTUNITY_OPPORTUNITY (
	ID VARCHAR(16777216) NOT NULL COMMENT 'Unique opportunity ID',
	NAME VARCHAR(16777216) COMMENT 'Opportunity name',
	ACCOUNT_ID VARCHAR(16777216) COMMENT 'Account ID',
	SAP_CUSTOMER_KEY VARCHAR(16777216) COMMENT 'SAP customer key',
	DESCRIPTION VARCHAR(16777216) COMMENT 'Opportunity description',
	STAGE_NAME VARCHAR(16777216) COMMENT 'Stage of the opportunity',
	PROBABILITY NUMBER(5,2) COMMENT 'Probability of winning the opportunity',
	AMOUNT NUMBER(18,2) COMMENT 'Opportunity amount',
	CURRENCY_ISO_CODE VARCHAR(16777216) DEFAULT 'USD' COMMENT 'Currency codes',
	CLOSE_DATE DATE COMMENT 'Date the opportunity was closed',
	CREATED_DATE TIMESTAMP_LTZ(9) COMMENT 'Date the opportunity was created',
	LAST_MODIFIED_DATE TIMESTAMP_LTZ(9) COMMENT 'Date the opportunity was last modified',
	LAST_ACTIVITY_DATE DATE COMMENT 'Date of the last activity',
	IS_CLOSED BOOLEAN DEFAULT FALSE COMMENT 'Whether the opportunity is closed',
	IS_WON BOOLEAN DEFAULT FALSE COMMENT 'Whether the opportunity was won',
	IS_DELETED BOOLEAN DEFAULT FALSE COMMENT 'Whether the opportunity is deleted',
	TYPE VARCHAR(16777216) COMMENT 'Type of opportunity',
	LEAD_SOURCE VARCHAR(16777216) COMMENT 'Source of the lead',
	FORECAST_CATEGORY VARCHAR(16777216) COMMENT 'Forecast category',
	FORECAST_CATEGORY_NAME VARCHAR(16777216) COMMENT 'Forecast category name',
	OWNER_ID VARCHAR(16777216) COMMENT 'ID of the opportunity owner',
	OWNER_NAME VARCHAR(16777216) COMMENT 'Name of the opportunity owner',
	CAMPAIGN_ID VARCHAR(16777216) COMMENT 'Campaign ID',
	PRIMARY_PRODUCT VARCHAR(16777216) COMMENT 'Primary product',
	COMPETITOR VARCHAR(16777216) COMMENT 'Competitor name',
	SAP_SALES_ORDER VARCHAR(16777216) COMMENT 'SAP sales order number',
	SAP_SALES_ORGANIZATION VARCHAR(16777216) COMMENT 'SAP sales organization',
	SAP_DISTRIBUTION_CHANNEL VARCHAR(16777216) COMMENT 'SAP distribution channel',
	FISCAL_QUARTER VARCHAR(16777216) COMMENT 'Fiscal quarter',
	FISCAL_YEAR NUMBER(4,0) COMMENT 'Fiscal year',
	primary key (ID)
);
create or replace TABLE SAP_SALES_360.SAP_BDC_L1.CRM_OPPORTUNITY_SALES_REP (
	REP_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique identifier of the representative.',
	FIRST_NAME VARCHAR(16777216) COMMENT 'First name of the representative.',
	LAST_NAME VARCHAR(16777216) COMMENT 'Last name of the representative.',
	FULL_NAME VARCHAR(16777216) COMMENT 'Full name of the sales representative.',
	EMAIL VARCHAR(16777216) COMMENT 'Email address of the representative.',
	TITLE VARCHAR(16777216) COMMENT 'Job title of the representative.',
	DEPARTMENT VARCHAR(16777216) COMMENT 'Department the representative belongs to.',
	REGION VARCHAR(16777216) COMMENT 'Geographic region assigned to the representative.',
	TERRITORY VARCHAR(16777216) COMMENT 'Geographic territory assigned to the representative.',
	MANAGER_ID VARCHAR(16777216) COMMENT 'Unique identifier of the representative''s manager.',
	MANAGER_NAME VARCHAR(16777216) COMMENT 'Name of the representative''s manager.',
	HIRE_DATE DATE COMMENT 'Date the representative was hired.',
	IS_ACTIVE BOOLEAN DEFAULT TRUE COMMENT 'Indicator of whether the representative is active.',
	QUOTA_AMOUNT NUMBER(18,2) COMMENT 'The sales quota amount assigned to the representative.',
	CREATED_DATE TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Date the representative''s record was created.',
	primary key (REP_ID)
);
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.CUSTOMER_CUSTOMER (
	CUSTOMER STRING NOT NULL COMMENT 'Customer IDs',
	CUSTOMERNAME STRING COMMENT 'Customer names',
	CUSTOMERFULLNAME STRING COMMENT 'Full customer names',
	BPCUSTOMERNAME STRING COMMENT 'Business partner customer names',
	BPCUSTOMERFULLNAME STRING COMMENT 'Business partner customer full names',
	CREATEDBYUSER STRING COMMENT 'User IDs of creators',
	CREATIONDATE DATE COMMENT 'Date of creation',
	ADDRESSID STRING COMMENT 'Unique identifier for an address',
	CUSTOMERCLASSIFICATION STRING COMMENT 'Customer classifications',
	VATREGISTRATION STRING COMMENT 'VAT registration numbers',
	CUSTOMERACCOUNTGROUP STRING COMMENT 'Customer account groups',
	AUTHORIZATIONGROUP STRING COMMENT 'Authorization groups',
	DELIVERYISBLOCKED STRING COMMENT 'Indication of whether delivery is blocked',
	POSTINGISBLOCKED STRING COMMENT 'Indication of whether posting is blocked',
	BILLINGISBLOCKEDFORCUSTOMER STRING COMMENT 'Indication of whether billing is blocked for a customer',
	ORDERISBLOCKEDFORCUSTOMER STRING COMMENT 'Indication of whether an order is blocked for a customer',
	INTERNATIONALLOCATIONNUMBER1 STRING COMMENT 'International location numbers',
	ISONETIMEACCOUNT STRING COMMENT 'Indication of whether an account is one-time',
	TAXJURISDICTION STRING COMMENT 'Tax jurisdictions',
	INDUSTRY STRING COMMENT 'Industries',
	COUNTRY STRING COMMENT 'Countries',
	ORGANIZATIONBPNAME1 STRING COMMENT 'Organization business partner names',
	ORGANIZATIONBPNAME2 STRING COMMENT 'Organization business partner names',
	CITYNAME STRING COMMENT 'City names',
	POSTALCODE STRING COMMENT 'Zip codes',
	STREETNAME STRING COMMENT 'Street names',
	SORTFIELD STRING COMMENT 'Field for sorting',
	FAXNUMBER STRING COMMENT 'Fax numbers',
	REGION STRING COMMENT 'Regions',
	TELEPHONENUMBER1 STRING COMMENT 'Phone numbers',
	TELEPHONENUMBER2 STRING COMMENT 'Phone numbers',
	LANGUAGE STRING COMMENT 'Languages',
	__OPERATION_TYPE STRING COMMENT 'Operation types',
	__TIMESTAMP STRING COMMENT 'Timestamps',
	LOAD_TYPE STRING COMMENT 'Load types',
	RUN_ID STRING COMMENT 'Unique identifier for a run'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'customer/customer.gF0fSTnG/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODINTLTRADECLASSIFICATION (
	TRDCLASSFCTNNMBRSCHM STRING,
	PRODUCT STRING,
	COMMODITYCODE STRING,
	VALIDITYSTARTDATE STRING,
	COUNTRY STRING,
	VALIDITYENDDATE STRING,
	TRDCLASSFCTNNMBRUUID STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/prodintltradeclassification.HB4vfBOt/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCT (
	PRODUCT STRING NOT NULL COMMENT 'Product name.',
	PRODUCTEXTERNALID STRING COMMENT 'External identifier for the product.',
	PRODUCTOID STRING COMMENT 'Unique identifier for the product.',
	PRODUCTTYPE STRING COMMENT 'Type of product.',
	CREATIONDATE DATE COMMENT 'Date the product was created.',
	CREATIONTIME STRING COMMENT 'Time the product was created.',
	CREATIONDATETIME TIMESTAMP_LTZ(6) COMMENT 'Date and time the product was created.',
	CREATEDBYUSER STRING COMMENT 'User who created the product.',
	LASTCHANGEDATE DATE COMMENT 'Date the product was last changed.',
	LASTCHANGEDBYUSER STRING COMMENT 'User who last changed the product.',
	ISMARKEDFORDELETION BOOLEAN COMMENT 'Flag indicating if the product is marked for deletion.',
	CROSSPLANTSTATUS STRING COMMENT 'Cross-plant status for the product.',
	PRODUCTGROUP STRING COMMENT 'Group the product belongs to.',
	BASEUNIT STRING COMMENT 'Unit of measurement for the product.',
	NETWEIGHT DOUBLE COMMENT 'Net weight of the product.',
	GROSSWEIGHT DOUBLE COMMENT 'Gross weight of the product.',
	WEIGHTUNIT STRING COMMENT 'Unit of measurement for the weight.',
	DIVISION STRING COMMENT 'Division the product belongs to.',
	COUNTRYOFORIGIN STRING COMMENT 'Country of origin for the product.',
	PRODUCTHIERARCHY STRING COMMENT 'Hierarchy of the product.',
	__OPERATION_TYPE STRING COMMENT 'Type of operation for the product.',
	__TIMESTAMP STRING COMMENT 'Timestamp for the product.',
	LOAD_TYPE STRING COMMENT 'Type of load for the product.',
	RUN_ID STRING COMMENT 'Unique identifier for the run.'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/product.Xk3i066d/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTDESCRIPTION (
	PRODUCT STRING NOT NULL COMMENT 'Product identifier.',
	LANGUAGE STRING NOT NULL COMMENT 'Language code.',
	PRODUCTDESCRIPTION STRING COMMENT 'Product description.',
	LANGUAGEISOCODE STRING COMMENT 'Two-letter code for the language.',
	__OPERATION_TYPE STRING COMMENT 'Type of operation performed.',
	__TIMESTAMP STRING COMMENT 'Timestamp in ISO 8601 format.',
	LOAD_TYPE STRING COMMENT 'Type of load.',
	RUN_ID STRING COMMENT 'Unique identifier for the run.'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/description.kZBJzwZ0/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTGROUP (
	PRODUCTGROUP STRING NOT NULL COMMENT 'Product group identifier.',
	AUTHORIZATIONGROUP STRING COMMENT 'Authorization group.',
	VALUATIONCLASS STRING COMMENT 'Valuation class.',
	PURCHASINGACKNPROFILE STRING COMMENT 'Purchasing acknowledgement profile.',
	__OPERATION_TYPE STRING COMMENT 'The type of operation performed.',
	__TIMESTAMP STRING COMMENT 'Date and time of the operation in ISO 8601 format.',
	LOAD_TYPE STRING COMMENT 'Type of load.',
	RUN_ID STRING COMMENT 'Unique identifier for the run.'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/group.1HVEaUbP/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTGROUPTEXT (
	PRODUCTGROUP STRING NOT NULL COMMENT 'The product group code.',
	LANGUAGE STRING NOT NULL COMMENT 'The language code.',
	PRODUCTGROUPNAME STRING COMMENT 'The name of the product group.',
	PRODUCTGROUPTEXT STRING COMMENT 'The text description of the product group.',
	__OPERATION_TYPE STRING COMMENT 'The type of operation performed.',
	__TIMESTAMP STRING COMMENT 'The timestamp of the operation.',
	LOAD_TYPE STRING COMMENT 'The type of load.',
	RUN_ID STRING COMMENT 'A unique identifier for the run.'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/grouptext.wClQlFqu/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTMRPAREA (
	PRODUCT STRING,
	MRPAREA STRING,
	MRPPLANT STRING,
	MRPGROUP STRING,
	MRPTYPE STRING,
	MRPCONTROLLER STRING,
	MRPPROFILE STRING,
	LOTSIZINGPROCEDURE STRING,
	MRPPLANNINGCALENDAR STRING,
	MRPPLANNINGCYCLE STRING,
	MRPSAFETYSTOCKMETHOD STRING,
	MATERIALPROCUREMENTPROFILE STRING,
	PRODUCTIONSTORAGELOCATION STRING,
	DFLTSTORLOCFOREXTPROCMT STRING,
	RANGEOFCOVERAGEPROFILE STRING,
	SAFETYTIMEPERIODPROFILE STRING,
	PRODUCTSAFETYTIMEMRPRELEVANCE STRING,
	DEPENDENTRQMTMRPRELEVANCE STRING,
	STORAGECOSTSPERCENTAGECODE STRING,
	ROUNDINGPROFILE STRING,
	ISMARKEDFORDELETION STRING,
	LASTCHANGEDBYUSER STRING,
	LASTCHANGEDATE STRING,
	LASTCHANGETIME STRING,
	PLANNEDDELIVERYDURATIONINDAYS STRING,
	PLANNINGTIMEFENCEINDAYS STRING,
	RQMTQTYRCPTTAKTTMEINWRKGDAYS STRING,
	ASSEMBLYSCRAPPERCENT STRING,
	BASEUNIT STRING,
	MINIMUMLOTSIZEQUANTITY STRING,
	MAXIMUMLOTSIZEQUANTITY STRING,
	MATERIALMAXSTOCKLEVELQUANTITY STRING,
	SAFETYSTOCKQUANTITY STRING,
	LOTSIZEROUNDINGQUANTITY STRING,
	REORDERTHRESHOLDQUANTITY STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productmrparea.mGQpC320/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANT (
	PRODUCT STRING,
	PLANT STRING,
	PURCHASINGGROUP STRING,
	COUNTRYOFORIGIN STRING,
	REGIONOFORIGIN STRING,
	PRODUCTIONINVTRYMANAGEDLOC STRING,
	PROFILECODE STRING,
	PROFILEVALIDITYSTARTDATE STRING,
	AVAILABILITYCHECKTYPE STRING,
	FISCALYEARVARIANT STRING,
	PERIODTYPE STRING,
	PROFITCENTER STRING,
	GOODSRECEIPTDURATION STRING,
	MAINTENANCESTATUSNAME STRING,
	ISMARKEDFORDELETION STRING,
	MRPTYPE STRING,
	MRPRESPONSIBLE STRING,
	ABCINDICATOR STRING,
	MINIMUMLOTSIZEQUANTITY STRING,
	MAXIMUMLOTSIZEQUANTITY STRING,
	FIXEDLOTSIZEQUANTITY STRING,
	CONSUMPTIONTAXCTRLCODE STRING,
	ISCOPRODUCT STRING,
	CONFIGURABLEPRODUCT STRING,
	STOCKDETERMINATIONGROUP STRING,
	HASPOSTTOINSPECTIONSTOCK STRING,
	ISBATCHMANAGEMENTREQUIRED STRING,
	SERIALNUMBERPROFILE STRING,
	ISNEGATIVESTOCKALLOWED STRING,
	HASCONSIGNMENTCTRL STRING,
	ISPURGACROSSPURGGROUP STRING,
	ISINTERNALBATCHMANAGED STRING,
	PRODUCTCFOPCATEGORY STRING,
	PRODUCTISEXCISETAXRELEVANT STRING,
	UNDERDELIVTOLERANCELIMIT STRING,
	OVERDELIVTOLERANCELIMIT STRING,
	PROCUREMENTTYPE STRING,
	SPECIALPROCUREMENTTYPE STRING,
	PRODUCTIONSCHEDULINGPROFILE STRING,
	PRODUCTIONSUPERVISOR STRING,
	SAFETYSTOCKQUANTITY STRING,
	GOODSISSUEUNIT STRING,
	SOURCEOFSUPPLYCATEGORY STRING,
	CONSUMPTIONREFERENCEPRODUCT STRING,
	CONSUMPTIONREFERENCEPLANT STRING,
	CONSUMPTIONREFUSAGEENDDATE STRING,
	CONSUMPTIONQTYMULTIPLIER STRING,
	PRODUCTUNITGROUP STRING,
	DISTRCNTRDISTRIBUTIONPROFILE STRING,
	CONSIGNMENTCONTROL STRING,
	GOODISSUEPROCESSINGDAYS STRING,
	PLANNEDDELIVERYDURATIONINDAYS STRING,
	PRODUCTISCRITICALPRT STRING,
	PRODUCTLOGISTICSHANDLINGGROUP STRING,
	MATERIALFREIGHTGROUP STRING,
	ORIGINALBATCHREFERENCEMATERIAL STRING,
	ORIGLBATCHMANAGEMENTISREQUIRED STRING,
	PRODUCTCONFIGURATION STRING,
	PRODUCTMINCONTROLTEMPERATURE STRING,
	PRODUCTMAXCONTROLTEMPERATURE STRING,
	PRODUCTCONTROLTEMPERATUREUNIT STRING,
	VALUATIONCATEGORY STRING,
	BASEUNIT STRING,
	ITEMUNIQUEIDENTIFIERISRELEVANT STRING,
	ITEMUNIQUEIDENTIFIERTYPE STRING,
	EXTALLOCOFITMUNQIDTISRELEVANT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplant.BK9yKaE4/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTCOSTING (
	PRODUCT STRING,
	PLANT STRING,
	ISCOPRODUCT STRING,
	COSTINGLOTSIZE STRING,
	TASKLISTGROUP STRING,
	TASKLISTTYPE STRING,
	COSTINGSPECIALPROCUREMENTTYPE STRING,
	SOURCEBOMALTERNATIVE STRING,
	PRODUCTBOMUSAGE STRING,
	PRODUCTISCOSTINGRELEVANT STRING,
	TASKLISTGROUPCOUNTER STRING,
	VARIANCEKEY STRING,
	COSTINGPRODUCTIONVERSION STRING,
	ISFIXEDPRICECOPRODUCT STRING,
	BASEUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantcosting.8ofZqSEY/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTFORECAST (
	PRODUCT STRING,
	PLANT STRING,
	CONSUMPTIONREFUSAGEENDDATE STRING,
	CONSUMPTIONQTYMULTIPLIER STRING,
	CONSUMPTIONREFERENCEPRODUCT STRING,
	CONSUMPTIONREFERENCEPLANT STRING,
	CORRECTIONFACTORISREQUIRED STRING,
	FORECASTMODELISRESET STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantforecast.IwjU5NOJ/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTINTERNATIONALTRADE (
	PRODUCT STRING,
	PLANT STRING,
	COUNTRYOFORIGIN STRING,
	REGIONOFORIGIN STRING,
	CONSUMPTIONTAXCTRLCODE STRING,
	EXPORTANDIMPORTPRODUCTGROUP STRING,
	PRODUCTCASNUMBER STRING,
	COMMODITIYCODENUMBERUNIT STRING,
	PRODINTLTRADECLASSIFICATION STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantinternationaltrade.SUWQ4a3z/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTPROCUREMENT (
	PRODUCT STRING,
	PLANT STRING,
	ISAUTOPURORDCREATIONALLOWED STRING,
	ISSOURCELISTREQUIRED STRING,
	ISPURGACROSSPURGGROUP STRING,
	SOURCEOFSUPPLYCATEGORY STRING,
	PURCHASINGGROUP STRING,
	ISACTIVEENTITY STRING,
	PROPOSEDPRODUCTSUPPLYAREA STRING,
	ITMISRLVTTOJITDELIVSCHEDULES STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantprocurement.Q3M3sGqf/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTPURCHASETAX (
	PRODUCT STRING,
	SOURCELOCATIONCOUNTRY STRING,
	TAXINDICATOR STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantpurchasetax.XL4vO9eK/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTSTORAGE (
	PRODUCT STRING,
	PLANT STRING,
	INVENTORYFORCYCLECOUNTIND STRING,
	MAXIMUMSTORAGEPERIOD STRING,
	PROVISIONINGSERVICELEVEL STRING,
	ISACTIVEENTITY STRING,
	PRODMAXIMUMSTORAGEPERIODUNIT STRING,
	WRHSMGMTPTWYANDSTKREMOVALSTRGY STRING,
	CYCLECOUNTINGINDICATORISFIXED STRING,
	SEGMENTATIONSTRATEGYFORPLANT STRING,
	DEFAULTSEGMENTVALUE STRING,
	SGMTHASPRIOINPRODUCTSTOCKSORT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantstorage.iAa3gGeF/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPLANTSUPPLYPLANNING (
	PRODUCT STRING,
	PLANT STRING,
	FIXEDLOTSIZEQUANTITY STRING,
	MAXIMUMLOTSIZEQUANTITY STRING,
	MINIMUMLOTSIZEQUANTITY STRING,
	LOTSIZEROUNDINGQUANTITY STRING,
	LOTSIZINGPROCEDURE STRING,
	MRPTYPE STRING,
	MRPRESPONSIBLE STRING,
	SAFETYSTOCKQUANTITY STRING,
	MINIMUMSAFETYSTOCKQUANTITY STRING,
	PLANNINGTIMEFENCE STRING,
	CONSUMPTIONVALUECATEGORY STRING,
	MAXIMUMSTOCKQUANTITY STRING,
	REORDERTHRESHOLDQUANTITY STRING,
	PLANNEDDELIVERYDURATIONINDAYS STRING,
	SAFETYSUPPLYDURATIONINDAYS STRING,
	PLANNINGSTRATEGYGROUP STRING,
	TOTALREPLENISHMENTLEADTIME STRING,
	PROCUREMENTTYPE STRING,
	PROCUREMENTSUBTYPE STRING,
	ASSEMBLYSCRAPPERCENT STRING,
	AVAILABILITYCHECKTYPE STRING,
	GOODSRECEIPTDURATION STRING,
	PLANANDORDERDAYDETERMINATION STRING,
	ROUNDINGPROFILE STRING,
	DFLTSTORAGELOCATIONEXTPROCMT STRING,
	GOODISSUEPROCESSINGDAYS STRING,
	CONSIGNMENTCONTROL STRING,
	ISACTIVEENTITY STRING,
	MRPGROUP STRING,
	LOTSIZEINDEPENDENTCOSTS STRING,
	STORAGECOSTSPERCENTAGECODE STRING,
	RQMTQTYRCPTTAKTTMEINWRKGDAYS STRING,
	MRPPLANNINGCALENDAR STRING,
	RANGEOFCVRGPRFLCODE STRING,
	PRODUCTSAFETYTIMEMRPRELEVANCE STRING,
	SAFETYTIMEPERIODPROFILE STRING,
	DEPENDENTRQMTMRPRELEVANCE STRING,
	PRODUCTSERVICELEVELINPERCENT STRING,
	PRODINHPRODNDURATIONINWORKDAYS STRING,
	MRPAVAILABILITYTYPE STRING,
	CROSSPROJECTPRODUCT STRING,
	PRODNPLNGANDCONTROLCALENDAR STRING,
	FOLLOWUPPRODUCT STRING,
	REPETITIVEMANUFACTURINGISALLWD STRING,
	DEPENDENTREQUIREMENTSTYPE STRING,
	PRODUCTISBULKCOMPONENT STRING,
	REPETITIVEMANUFACTURINGPROFILE STRING,
	BACKWARDCNSMPNPERIODINWORKDAYS STRING,
	FWDCONSUMPTIONPERIODINWORKDAYS STRING,
	PRODRQMTSCONSUMPTIONMODE STRING,
	PRODFCSTREQUIREMENTSSPLITCODE STRING,
	EFFECTIVEOUTDATE STRING,
	MRPPROFILE STRING,
	SCHEDULINGFLOATPROFILE STRING,
	COMPONENTSCRAPINPERCENT STRING,
	PRODUCTDISCONTINUATIONCODE STRING,
	PRODUCTREQUIREMENTSGROUPING STRING,
	PRODUCTIONINVTRYMANAGEDLOC STRING,
	PRODUCTCOMPONENTBACKFLUSHCODE STRING,
	PROPOSEDPRODUCTSUPPLYAREA STRING,
	PLANNEDORDERACTIONCONTROL STRING,
	PRODUCTUNITGROUP STRING,
	MRPSAFETYSTOCKMETHOD STRING,
	JITPRODNCONFPROFILE STRING,
	CURRENCY STRING,
	COMPANYCODE STRING,
	VALUATIONAREA STRING,
	BASEUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productplantsupplyplanning.WxhI7tOO/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTPROCUREMENT (
	PRODUCT STRING,
	PURCHASEORDERQUANTITYUNIT STRING,
	VARBLPURORDUNITSTATUS STRING,
	PURCHASINGACKNPROFILE STRING,
	PROCUREMENTRULE STRING,
	SOURCEOFSUPPLYCATEGORY STRING,
	PURCHASINGGROUP STRING,
	ISACTIVEENTITY STRING,
	AUTHORIZATIONGROUP STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productprocurement.gQfTHXfw/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTQUALITYMANAGEMENT (
	PRODUCT STRING,
	QLTYMGMTINPROCMTISACTIVE STRING,
	AUTHORIZATIONGROUP STRING,
	CATALOGPROFILE STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productqualitymanagement.iquX0P84/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTSALES (
	PRODUCT STRING,
	SALESSTATUS STRING,
	SALESSTATUSVALIDITYDATE STRING,
	TAXCLASSIFICATION STRING,
	TRANSPORTATIONGROUP STRING,
	ALLOWEDPACKAGINGWEIGHTQTY STRING,
	ALLOWEDPACKAGINGWEIGHTQTYUNIT STRING,
	ALLOWEDPACKAGINGVOLUMEQTY STRING,
	ALLOWEDPACKAGINGVOLUMEQTYUNIT STRING,
	PRICINGREFERENCEPRODUCT STRING,
	VARIANTSPRICINGPROFILE STRING,
	ISVARIANTPRICEALLOWED STRING,
	LOADINGGROUP STRING,
	ISACTIVEENTITY STRING,
	EXCESSWEIGHTTOLERANCE STRING,
	EXCESSVOLUMETOLERANCE STRING,
	PACKAGINGMATERIALTYPE STRING,
	ISCLOSEDPACKAGINGMATERIAL STRING,
	VOLUMEMAXIMUMLEVEL STRING,
	AUTHORIZATIONGROUP STRING,
	MATERIALFREIGHTGROUP STRING,
	STACKINGFACTOR STRING,
	SERVICEDURATION STRING,
	SERVICEDURATIONUNIT STRING,
	SERVICEPROFILE STRING,
	RESPONSEPROFILE STRING,
	CABILLGCYCLE STRING,
	SUBSCRPNPRODBILLGCYCDETN STRING,
	SUBSCRPNPRODTECHRSCESCHEMA STRING,
	CONTRACTAUTORENEWALTYPE STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productsales.khN1vE8u/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTSALESDELIVERY (
	PRODUCT STRING,
	PRODUCTSALESORG STRING,
	PRODUCTDISTRIBUTIONCHNL STRING,
	MINIMUMORDERQUANTITY STRING,
	SUPPLYINGPLANT STRING,
	PRICESPECIFICATIONPRODUCTGROUP STRING,
	ACCOUNTDETNPRODUCTGROUP STRING,
	DELIVERYNOTEPROCMINDELIVQTY STRING,
	ITEMCATEGORYGROUP STRING,
	DELIVERYQUANTITYUNIT STRING,
	DELIVERYQUANTITY STRING,
	PRODUCTSALESSTATUS STRING,
	PRODUCTSALESSTATUSVALIDITYDATE STRING,
	SALESMEASUREUNIT STRING,
	ISMARKEDFORDELETION STRING,
	PRODUCTHIERARCHY STRING,
	FIRSTSALESSPECPRODUCTGROUP STRING,
	SECONDSALESSPECPRODUCTGROUP STRING,
	THIRDSALESSPECPRODUCTGROUP STRING,
	FOURTHSALESSPECPRODUCTGROUP STRING,
	FIFTHSALESSPECPRODUCTGROUP STRING,
	MINIMUMMAKETOORDERORDERQTY STRING,
	LOGISTICSSTATISTICSGROUP STRING,
	VOLUMEREBATEGROUP STRING,
	PRODUCTCOMMISSIONGROUP STRING,
	CASHDISCOUNTISDEDUCTIBLE STRING,
	PRICINGREFERENCEPRODUCT STRING,
	ASSORTMENTGRADE STRING,
	STORELISTINGPROCEDURE STRING,
	DISTRCNTRLISTINGPROCEDURE STRING,
	STORELISTINGSTARTDATE STRING,
	STORELISTINGENDDATE STRING,
	DISTRCNTRLISTINGSTARTDATE STRING,
	DISTRCNTRLISTINGENDDATE STRING,
	STORESALESTARTDATE STRING,
	STORESALEENDDATE STRING,
	DISTRCNTRSALESTARTDATE STRING,
	DISTRCNTRSALEENDDATE STRING,
	ROUNDINGPROFILE STRING,
	PRODUCTUNITGROUP STRING,
	MAXDELIVERYQTYSTOREORDER STRING,
	PRICEFIXINGCATEGORY STRING,
	VARIABLESALESUNITISNOTALLOWED STRING,
	COMPETITIONPRESSURECATEGORY STRING,
	PRODUCTHASATTRIBUTEID01 STRING,
	PRODUCTHASATTRIBUTEID02 STRING,
	PRODUCTHASATTRIBUTEID03 STRING,
	PRODUCTHASATTRIBUTEID04 STRING,
	PRODUCTHASATTRIBUTEID05 STRING,
	PRODUCTHASATTRIBUTEID06 STRING,
	PRODUCTHASATTRIBUTEID07 STRING,
	PRODUCTHASATTRIBUTEID08 STRING,
	PRODUCTHASATTRIBUTEID09 STRING,
	PRODUCTHASATTRIBUTEID10 STRING,
	ISACTIVEENTITY STRING,
	PRODEXTASSORTMENTPRIORITY STRING,
	PRODISENTLMNTRLVT STRING,
	BASEUNIT STRING,
	SUBSCRPNCONTRDFLTDURATION STRING,
	SUBSCRPNCONTRALTVDURATION1 STRING,
	SUBSCRPNCONTRALTVDURATION2 STRING,
	SUBSCRPNCONTRDURATIONUNIT STRING,
	SUBSCRPNCONTRDFLTEXTNDURN STRING,
	SUBSCRPNCONTRALTVEXTNDURN1 STRING,
	SUBSCRPNCONTRALTVEXTNDURN2 STRING,
	SUBSCRPNCONTREXTNDURNUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productsalesdelivery.9hAhzBob/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTSTORAGE (
	PRODUCT STRING,
	STORAGECONDITIONS STRING,
	TEMPERATURECONDITIONIND STRING,
	HAZARDOUSMATERIALNUMBER STRING,
	NMBROFGRORGISLIPSTOPRINTQTY STRING,
	LABELTYPE STRING,
	LABELFORM STRING,
	MINREMAININGSHELFLIFE STRING,
	PRODUCTEXPIRATIONDATECODE STRING,
	STORAGEBININSTRUCTION STRING,
	TOTALSHELFLIFESTORAGEPERCENT STRING,
	SHELFLIFEEXPIRATIONDATEPERIOD STRING,
	SHELFLIFEEXPRTNDATERNDNGRULE STRING,
	AUTHORIZATIONGROUP STRING,
	ISACTIVEENTITY STRING,
	TOTALSHELFLIFE STRING,
	BASEUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productstorage.P5CwAoM7/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTUNITOFMEASURE (
	PRODUCT STRING,
	ALTERNATIVEUNIT STRING,
	QUANTITYNUMERATOR STRING,
	QUANTITYDENOMINATOR STRING,
	MATERIALVOLUME STRING,
	VOLUMEUNIT STRING,
	GROSSWEIGHT STRING,
	WEIGHTUNIT STRING,
	GLOBALTRADEITEMNUMBER STRING,
	GLOBALTRADEITEMNUMBERCATEGORY STRING,
	UNITSPECIFICPRODUCTLENGTH STRING,
	UNITSPECIFICPRODUCTWIDTH STRING,
	UNITSPECIFICPRODUCTHEIGHT STRING,
	PRODUCTMEASUREMENTUNIT STRING,
	LOWERLEVELPACKAGINGUNIT STRING,
	REMAININGVOLUMEAFTERNESTING STRING,
	MAXIMUMSTACKINGFACTOR STRING,
	CAPACITYUSAGE STRING,
	ISACTIVEENTITY STRING,
	UNITOFMEASURECATEGORY STRING,
	PRODUCTGTINVARIANT STRING,
	BASEUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productunitofmeasure.tDlMf1sS/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTUNITOFMEASUREEAN (
	PRODUCT STRING,
	ALTERNATIVEUNIT STRING,
	CONSECUTIVENUMBER STRING,
	PRODUCTSTANDARDID STRING,
	INTERNATIONALARTICLENUMBERCAT STRING,
	ISMAINGLOBALTRADEITEMNUMBER STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productunitofmeasureean.TiFbKV24/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTVALUATION (
	PRODUCT STRING,
	VALUATIONAREA STRING,
	VALUATIONTYPE STRING,
	VALUATIONCLASS STRING,
	PRICEDETERMINATIONCONTROL STRING,
	FISCALMONTHCURRENTPERIOD STRING,
	FISCALYEARCURRENTPERIOD STRING,
	STANDARDPRICE STRING,
	PRICEUNITQTY STRING,
	INVENTORYVALUATIONPROCEDURE STRING,
	FUTUREPRICEVALIDITYSTARTDATE STRING,
	PREVINVTRYPRICEINCOCODECRCY STRING,
	MOVINGAVERAGEPRICE STRING,
	VALUATIONCATEGORY STRING,
	PRODUCTUSAGETYPE STRING,
	PRODUCTORIGINTYPE STRING,
	ISPRODUCEDINHOUSE STRING,
	PRODCOSTESTNUMBER STRING,
	ISMARKEDFORDELETION STRING,
	VALUATIONMARGIN STRING,
	ISACTIVEENTITY STRING,
	COMPANYCODE STRING,
	VALUATIONCLASSSALESORDERSTOCK STRING,
	PROJECTSTOCKVALUATIONCLASS STRING,
	TAXBASEDPRICESPRICEUNITQTY STRING,
	PRICELASTCHANGEDATE STRING,
	FUTUREPRICE STRING,
	MAINTENANCESTATUS STRING,
	CURRENCY STRING,
	BASEUNIT STRING,
	MLISACTIVEATPRODUCTLEVEL STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productvaluation.wtRdDnPk/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTVALUATIONACCOUNTING (
	PRODUCT STRING,
	VALUATIONAREA STRING,
	VALUATIONTYPE STRING,
	COMMERCIALPRICE1INCOCODECRCY STRING,
	COMMERCIALPRICE2INCOCODECRCY STRING,
	COMMERCIALPRICE3INCOCODECRCY STRING,
	DEVALUATIONYEARCOUNT STRING,
	FUTUREPRICE STRING,
	FUTUREPRICEVALIDITYSTARTDATE STRING,
	ISLIFOANDFIFORELEVANT STRING,
	LIFOVALUATIONPOOLNUMBER STRING,
	STANDARDPRICEPREVYEAR STRING,
	TAXPRICEL1INCOCODECRCY STRING,
	TAXPRICE2INCOCODECRCY STRING,
	TAXPRICE3INCOCODECRCY STRING,
	TAXBASEDPRICESPRICEUNITQTY STRING,
	COMPANYCODE STRING,
	CURRENCY STRING,
	BASEUNIT STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productvaluationaccounting.JLkcmL5b/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.PRODUCT_PRODUCTVALUATIONCOSTING (
	PRODUCT STRING,
	VALUATIONAREA STRING,
	VALUATIONTYPE STRING,
	ISMATERIALCOSTEDWITHQTYSTRUC STRING,
	ISMATERIALRELATEDORIGIN STRING,
	COSTORIGINGROUP STRING,
	COSTINGOVERHEADGROUP STRING,
	PLANNEDPRICE1INCOCODECRCY STRING,
	PLANNEDPRICE2INCOCODECRCY STRING,
	PLANNEDPRICE3INCOCODECRCY STRING,
	FUTUREPLNDPRICE1VALDTYDATE STRING,
	FUTUREPLNDPRICE2VALDTYDATE STRING,
	FUTUREPLNDPRICE3VALDTYDATE STRING,
	PLANNEDPRICE STRING,
	CURRENCY STRING,
	COMPANYCODE STRING,
	__OPERATION_TYPE STRING,
	__TIMESTAMP STRING,
	LOAD_TYPE_8995A2862A8343BD8390AAA82C46E881 STRING,
	RUN_ID_8995A2862A8343BD8390AAA82C46E881 STRING
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'product/productvaluationcosting.RDSg0pjM/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.SALESORDERS_SALESORDER (
	SALESORDER STRING NOT NULL COMMENT 'Sales order number.',
	SALESORDERTYPE STRING COMMENT 'Type of sales order.',
	SALESORDERPROCESSINGTYPE STRING COMMENT 'Type of sales order processing.',
	CREATEDBYUSER STRING COMMENT 'User who created the sales order.',
	LASTCHANGEDBYUSER STRING COMMENT 'User who last changed the sales order.',
	CREATIONDATE DATE COMMENT 'Date the sales order was created.',
	CREATIONTIME STRING COMMENT 'Time the sales order was created.',
	LASTCHANGEDATE DATE COMMENT 'Date the sales order was last changed.',
	LASTCHANGEDATETIME TIMESTAMP_LTZ(6) COMMENT 'Date and time the sales order was last changed.',
	SALESORGANIZATION STRING COMMENT 'Sales organization.',
	DISTRIBUTIONCHANNEL STRING COMMENT 'Distribution channel.',
	ORGANIZATIONDIVISION STRING COMMENT 'Organization division.',
	SALESGROUP STRING COMMENT 'Sales group.',
	SALESOFFICE STRING COMMENT 'Sales office.',
	SOLDTOPARTY STRING COMMENT 'Party sold to.',
	CUSTOMERGROUP STRING COMMENT 'Customer group.',
	SALESORDERDATE DATE COMMENT 'Date the sales order was made.',
	PURCHASEORDERBYCUSTOMER STRING COMMENT 'Customer''s purchase order number.',
	CUSTOMERPURCHASEORDERDATE DATE COMMENT 'Customer''s purchase order date.',
	TOTALNETAMOUNT DOUBLE COMMENT 'Total net amount of the sales order.',
	TRANSACTIONCURRENCY STRING COMMENT 'Transaction currency.',
	PRICINGDATE DATE COMMENT 'Date the sales order was priced.',
	INCOTERMSCLASSIFICATION STRING COMMENT 'Incoterms classification.',
	INCOTERMSLOCATION1 STRING COMMENT 'Incoterms location 1.',
	INCOTERMSLOCATION2 STRING COMMENT 'Incoterms location 2.',
	REQUESTEDDELIVERYDATE DATE COMMENT 'Requested delivery date.',
	CUSTOMERPAYMENTTERMS STRING COMMENT 'Customer payment terms.',
	__OPERATION_TYPE STRING COMMENT 'Operation type.',
	__TIMESTAMP STRING COMMENT 'Timestamp.',
	LOAD_TYPE STRING COMMENT 'Load type.',
	RUN_ID STRING COMMENT 'Run ID.'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'sales/order.P53xT9sH/';
create or replace ICEBERG TABLE SAP_SALES_360.SAP_BDC_L1.SALESORDERS_SALESORDERITEM (
	SALESORDER STRING NOT NULL COMMENT 'Unique identifier for the sales order',
	SALESORDERITEM STRING NOT NULL COMMENT 'Unique identifier for the sales order item',
	SALESORDERITEMUUID STRING COMMENT 'Unique identifier for the sales order item',
	SALESORDERITEMCATEGORY STRING COMMENT 'Category of the sales order item',
	SALESORDERITEMTYPE STRING COMMENT 'Type of sales order item',
	ISRETURNSITEM STRING COMMENT 'Whether the item is a return',
	CREATEDBYUSER STRING COMMENT 'User who created the sales order item',
	CREATIONDATE DATE COMMENT 'Date the sales order item was created',
	DIVISION STRING COMMENT 'Division',
	MATERIAL STRING COMMENT 'Product material',
	PRODUCT STRING COMMENT 'Product',
	MATERIALGROUP STRING COMMENT 'Material group',
	PRODUCTGROUP STRING COMMENT 'Product group',
	PLANT STRING COMMENT 'Plant',
	SALESORDERITEMTEXT STRING COMMENT 'Text description of the sales order item',
	ORDERQUANTITY DOUBLE COMMENT 'Quantity ordered',
	ORDERQUANTITYUNIT STRING COMMENT 'Unit of measurement for the ordered quantity',
	NETAMOUNT DOUBLE COMMENT 'Net amount',
	TRANSACTIONCURRENCY STRING COMMENT 'Currency of the transaction',
	PRICINGDATE DATE COMMENT 'Date of pricing',
	NETPRICEAMOUNT DOUBLE COMMENT 'Net price amount',
	__OPERATION_TYPE STRING COMMENT 'Operation type',
	__TIMESTAMP STRING COMMENT 'Timestamp',
	LOAD_TYPE STRING COMMENT 'Load type',
	RUN_ID STRING COMMENT 'Run ID'
)
 EXTERNAL_VOLUME = 'SAP_ICEBERG_S3_VOLUME'
 ICEBERG_VERSION = 2
 CATALOG = 'SNOWFLAKE'
 BASE_LOCATION = 'sales/orderitem.CceY83HK/';
create or replace TABLE SAP_SALES_360.SAP_BDC_L1.SALES_FORECAST (
	FORECAST_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique identifier for each forecast record (UUID)',
	FISCAL_YEAR NUMBER(4,0) NOT NULL COMMENT 'Fiscal year of the forecast period (e.g. 2023, 2024, 2025)',
	FISCAL_MONTH NUMBER(2,0) NOT NULL COMMENT 'Fiscal month of the forecast period (1-12)',
	FORECAST_DATE DATE NOT NULL COMMENT 'First day of the forecast month — used as the period anchor date',
	SALESORGANIZATION VARCHAR(16777216) NOT NULL COMMENT 'SAP Sales Organization code (e.g. 1710, F1US, AUC1, USC1, DEC1)',
	SOLDTOPARTY VARCHAR(16777216) NOT NULL COMMENT 'SAP Customer number (sold-to party) the forecast applies to',
	PRODUCTGROUP VARCHAR(16777216) COMMENT 'SAP Product Group code for the forecasted product category',
	FORECAST_AMOUNT FLOAT COMMENT 'Forecasted revenue amount in the transaction currency',
	FORECAST_QUANTITY FLOAT COMMENT 'Forecasted number of order units for the period',
	FORECAST_VERSION VARCHAR(16777216) NOT NULL COMMENT 'Forecast scenario version — PLAN (baseline), REVISED (mid-cycle adjustment), or STRETCH (aggressive target)',
	CURRENCY VARCHAR(16777216) DEFAULT 'USD' COMMENT 'ISO currency code for the forecast amount (default USD)',
	CREATED_DATE TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Timestamp when the forecast record was created'
)COMMENT='Monthly sales forecast by org, customer, and product group — used for actual vs forecast reporting'
;
